### ISSUE TITLE
Figure labels

### ISSUE THREAD

**Issue by HJAllen** [lierdakil/pandoc-crossref#19]
I have updated to the latest version but still get figure labels as

fig 1.

I have added to the yaml header

```
figureTitle: 'Figure'
tableTitle: 'Table'
```
using RStudio-knitr-pandoc writing output to word .docx

Thanks,

Joel

**Comment by lierdakil** [comment]
`Title` is for *captions*. Try `figurePrefix`.

**Comment by lierdakil** [comment]
Or maybe I misunderstood your problem.

**Comment by lierdakil** [comment]
Not sure on RStudio-knitr, and how it handles things, but in order for pandoc-crossref to number your figures, you *have* to attach identifier to them, i.e. this `![Figure](image.png)` would be "just a figure", without number, while this `![Figure](image.png){#fig:fig1}` would be a numbered figure.

You can omit label, i.e. just have `![Figure](image.png){#fig:}`, but that would mess with `\listoffigures`, since it's build based on figure labels (which I should probably fix somewhere down the line)

**Comment by HJAllen** [comment]
Thanks for the quick response. To be clear, I want the reference in the text for the figure to be 'Figure x.'
The figure is an image inserted as
```
![Organization Chart](HABOrgChart.jpg) {#fig:orgStruct}
```
and the reference in the text is
[@fig:orgStruct]

**Comment by HJAllen** [comment]
The YAML header is:
```
---
title: "Title"
output: 
  word_document:
    pandoc_args:
    - --filter
    - pandoc-crossref
    - --filter
    - pandoc-word-newpage
    fig_width: 5
    fig_height: 5
    reference_docx: style_v1.docx
  pdf_document:
    includes:
      in_header: header.tex
    pandoc_args:
    - --filter
    - pandoc-crossref
  html_document:
    keep_md: yes
    pandoc_args:
    - --filter
    - pandoc-crossref
    - --filter
    - pandoc-word-newpage
csl: /workspace/cyanoHAB/environmental-toxicology-and-chemistry.csl
bibliography: HAB.bib
figurePrefix: 'Figure'
tablePrefix: 'Table'
---
```
