### ISSUE TITLE
Compatibility with pandoc 2.9.

### ISSUE THREAD

**Issue by CGMossa** [lierdakil/pandoc-crossref#244]
I recently upgraded to pandoc 2.9. There are lots of vital and exciting updates to pandoc, but it is not yet compatible with pandoc-crossref. 
I tried to upgrade the configuration-file with the new packages and also build pandoc itself with `stack`. It wasn't simple, and I had to enable `allow-newer` in order to do it.

**Comment by CGMossa** [comment]
This is my current `stack.yaml`-file:
```yml
flags:
  pandoc-crossref:
    enable_flaky_tests: true
ghc-options:
  $targets: -optl-fuse-ld=bfd
packages:
- .
allow-newer: true
extra-deps:
- roman-numerals-0.5.1.5
- pandoc-2.9
- HsYAML-0.2.1.0
- doclayout-0.2.0.1
- doctemplates-0.8.1
- haddock-library-1.8.0
- skylighting-0.8.3.2
- skylighting-core-0.8.3.2
- texmath-0.12
- pandoc-types-1.20
- regex-pcre-builtin-0.95.1.1.8.43
- regex-base-0.94.0.0
- emojis-0.1
resolver: lts-14.15
```

The problematic requirement is this `- doclayout-0.2.0.1`. If I make it `- doclayout-0.3`, then I get one complaint, and if I make it `- doclayout-0.2.0.1` I get another.

**Comment by lierdakil** [comment]
Uh. Hi. Latest pandoc-crossref is perfectly compatible with pandoc 2.9. I just probably need to update stack.yaml. Hold on.

**Comment by lierdakil** [comment]
Okay, I've pushed an updated `stack.yaml` to `master`. There were a couple snags, but overall it's all good, except stack's LTS _still_ only has pandoc-2.7.3, so I had to switch to nightly resolver as to avoid building my own snapshot basically. That's not an issue, unless you're going to develop Haskell applications on top of pandoc-crossref using stack.

Duplicating the updated `stack.yaml` here just in case.
```yaml
flags:
  pandoc-crossref:
    enable_flaky_tests: true
ghc-options:
  $targets: -optl-fuse-ld=bfd
packages:
- .
allow-newer: true # data-accessor-template overrestricts template-haskell dependency
extra-deps:
- roman-numerals-0.5.1.5
- data-accessor-template-0.2.1.16
resolver: nightly-2020-02-04
```
