### ISSUE TITLE
Has section numbering changed?

### ISSUE THREAD

**Issue by wlupton** [lierdakil/pandoc-crossref#254]
Hi. I tried out pandoc-crossref v0.4.0.0 today and am having trouble with section numbering (and more?). With the input file given below (and no command-line options other than this filter and input/output files), I get this:
```
pandoc-crossref v0.4.0.0 git commit 80080744cec5c9d0696d4e4be77bec5fc1cc2375 (HEAD) built with Pandoc v2.9.2.1, pandoc-types v1.20 and GHC 8.8.3
Undefined cross-reference: sec:section
Undefined cross-reference: sec:section
<h1 id="section">section</h1>
<p>This is <span class="citation" data-cites="sec:section">[@sec:section]</span>.</p>
```

But with the previous version I get this (which is what I want):
```
pandoc-crossref v0.3.6.2 git commit UNKNOWN (UNKNOWN) built with Pandoc v2.9.2, pandoc-types v1.20 and GHC 8.6.5
WARNING: pandoc-crossref was compiled with pandoc 2.9.2 but is being run through 2.9.2.1. This is not supported. Strange things may (and likely will) happen silently.
<h1 id="sec:section">1 section</h1>
<p>This is sec. 1.</p>
```

Here's the input file:
```
---
autoSectionLabels: true
numberSections: true
sectionsDepth: -1
---

# section

This is @sec:section.
```

**Comment by lierdakil** [comment]
There's a reason for major version change with v0.4.0.0. It uses completely different metadata syntax, and as of right now, there are little to no provisions for common use-cases (like section numbering) -- hence the "alpha" label -- so it requires a little bit of set-up. I did not yet update the docs, so your best bet is probably figuring it out from examples in tests: https://github.com/lierdakil/pandoc-crossref/tree/any-prefix/test/m2m

Your main issue here is that `autoSectionLabels` isn't a boolean field in v0.4, but requires a prefix you're going to use for sections, i.e. you need `autoSectionLabels: "sec"` or something like that.

You could use something like this for numbering (took this from tests):
```yaml
prefixes:
  sec:
    captionTemplate: '$$i$$$$titleDelim$$ $$t$$' # show part/etc numbers
    titleDelim: '.'
    numbering: arabic
    title: Chapter
    ref: ["chp.", "chps."]
    sub:
      # sub-sections can override any settings from parent
      # Here we want to have sections scoped to chapters, so
      scope: sec
      title: Section
      ref: ["sec.", "secs."]
      # We also want to show parent scope number in reference and title
      captionIndexTemplate: '$$s.i$$.$$ri$$'
      referenceIndexTemplate: '$$s.i$$.$$ri$$'
```

The system is much more flexible, but at the cost of complexity, as is plainly evident. I've been meaning to add some built-in templates for common use-cases (or to provide a semblance of backwards compatibility at least), but didn't get to it yet.
