### ISSUE TITLE
secLevelLabels with unique levels?

### ISSUE THREAD

**Issue by ricopicone** [lierdakil/pandoc-crossref#295]
My "numbering" scheme is one of abbreviation: each chapter gets a unique abbreviation like "intro" and similarly each section (e.g. "dyn"). This is motivated by my constant reshuffling of material and therefore numbers/references changing.

I have implemented this in LaTeX natively, and as I move over to Pandoc Markdown source, I think I'll be able to find a way to connect my LaTeX style to the output.

But for HTML output at least, I'm hoping to use pandoc-crossref. I was able to get close using `secLevelLabels` like the following.

```yaml
chapters: true
chaptersDepth: 2 # trick it into labeling by section
secLevelLabels:
  - ['']
  - ['sec1','sec2','sec3'] # eg
```

So I can consecutively define the section "numbers"/abbreviations ... this gives equations labels like `(.sec1.1)`. It would be nice to get rid of the leading `.`.

Ideally, though, I could define a unique section abbreviation for each unique chapter abbreviation. Essentially, I think this syntax would be how it could work.

```yaml
chapters: true
chaptersDepth: 2 # trick it into labeling by section
secLevelLabels:
  - ['ch1','ch2','ch3'] # etc
  - [
    ['sec1','sec2','sec3'], # for ch1
    ['foo1','foo2','foo3'], # for ch2
    ['bar1','bar2','bar3','bar4'] # for ch3
  ]
```

I'm not sure if nested arrays or dictionaries are better for section abbreviations. Anyhow, I'm guessing it wouldn't be terribly hard to extend this `secLevelLabels` option as I've described, but I don't know Haskell ... yet, anyhow!

(This is an excellent project, btw&mdash;great work!)
