### ISSUE TITLE
Cannot get `secPrefix` to work for References to Chapters and LaTeX/PDF output

### ISSUE THREAD

**Issue by thomasWeise** [lierdakil/pandoc-crossref#329]
Hi.

I am very sorry to disturb your work.
For some time now I am trying to get `secPrefix` to work in references to chapters in LaTeX/PDF output, but it seems to be ignored.

I think I am doing everything right.
I pass `--top-level-division=chapter` to pandoc.
In the metadata YAML section of the document, I write

```yaml
secPrefix:
  - "Abschnitt"
  - "Abschnitten"
 
cref: true
chapters: true
nameInLink: true
linkReferences: true
listings: false
codeBlockCaptions: true
 ```

If I write in the markdown:

```markdown
Danach können Sie ruhig [@sec:theChapter] lesen.

# Erstes Kapitel {#sec:theChapter}

Wilkommen zum ersten Kapitel.
```

This works for sections and for HTML output, where I get "`Danach können Sie ruhig Abschnitt 1 lesen.`" for that first line.
However, in the PDF output, I get "`Danach können Sie ruhig chapter 1 lesen.`"
In other words, the `secPrefix` here seems to be ignored and it write "`chapter 1`" instead.

What am I doing wrong?
(Again, sorry for asking, but I cannot seem to figure it out.)
If necessary, it would also do it via some `header-includes:` - but here I have no clue what would need to be done :-/

As a side note:
While I would be completely happy if I could get the above to work uniformly across HTML and PDF output, in the ideal case, I would like to be able to also specify something like `chapPrefix`, i.e., be able to do

```yaml
secPrefix:
  - "Abschnitt"
  - "Abschnitten"
chapPrefix:
  - "Kapitel"
  - "Kapitel"
  
cref: true
chapters: true
nameInLink: true
linkReferences: true
listings: false
codeBlockCaptions: true
 ```

because it would be nicer to have different prefixes for chapters and sections.
If something like that is already possible, then please let me know ... if not, then that is also OK (but if it is easy to realize, it could be a potential feature for a future release ^_^).

Many thanks,
   Thomas.
