### ISSUE TITLE
Any way to force equations to right of cell when using tableEqns?

### ISSUE THREAD

**Issue by jpk3333** [lierdakil/pandoc-crossref#343]
Hello, thanks so much for pandoc-crossref. It's worked perfectly for me to achieve numbered equations and cross-references to them when compiling from md to docx (which was a need that led me to abandon LaTeX and begin writing in Markdown).

I was just wondering: is there any way to force equations to be right-justified within their respective cells when using the tableEqns feature?

Thanks!

**Comment by lierdakil** [comment]
Not entirely sure what you're trying to achieve. A picture could be helpful.

**Comment by jpk3333** [comment]
Thanks. Pandoc-crossref w/ -MtableEqns works very nicely, but it center-justifies each equation and each number in their cells, as in this picture:
 
<img width="761" alt="Screen Shot 2022-03-04 at 9 43 44 AM" src="https://user-images.githubusercontent.com/99686982/156794874-cd7db8d0-267a-4215-8757-1a085aa811f6.png">

I would love the ability to force both the equation and the number to be right-justified in their cell, as in this picture:

<img width="766" alt="Screen Shot 2022-03-04 at 9 44 07 AM" src="https://user-images.githubusercontent.com/99686982/156795024-e0c7b218-13db-4441-93c2-7aa93697629a.png">

Thanks!

**Comment by lierdakil** [comment]
Hmm. The intention was for the cell with the equation number to be much narrower, so that the equation ends up being roughly centred. Something evidently goes wrong. AFAIU, you're targeting docx? What are you using to open the docx file?

If I understand correctly, the principal aim is to have the equation is in the horizontal centre of the page and the number is right-aligned, correct?

**Comment by jpk3333** [comment]
> AFAIU, you're targeting docx? What are you using to open the docx file?

That's right, docx; and I'm using Word to open the docx file.

> If I understand correctly, the principal aim is to have the equation is in the horizontal centre of the page and the number is right-aligned, correct?

That is correct, yes.

**Comment by lierdakil** [comment]
Which Word version, specifically? 365? What OS?

**Comment by jpk3333** [comment]
> Which Word version, specifically? 365? What OS?

Word version 16.58 (via a 365 subscription) on MacOS 11.4 (Big Sur).

**Comment by lierdakil** [comment]
Thanks. I'll see what I can figure out.

**Comment by lierdakil** [comment]
The bad news is I wasn't able to reproduce the rendering you're getting, unfortunately I have neither macOS nor Office 365 readily accessible. Where I tested (web version of Word 365, LibreOffice, Word 2013 and 2019 on Windows), it seemed to render more or less as expected.

The good news is, I've made the `tableEqns` layout configurable. See [here](https://lierdakil.github.io/pandoc-crossref/#equation-templates). This is as of yet unreleased, but you can grab a macOS binary from https://github.com/lierdakil/pandoc-crossref/releases/download/nightlies/pandoc-crossref-master-macOS-20220305-a359a9.tar.xz

NB: I think I might have messed up vertical alignment of equation numbers in tables, I'll see to fixing it later.

Right-aligning can be done with the following metadata for example:

```yaml
tableEqns: true
eqnBlockTemplate: |
  --------------------------------------------------------------- -------
                                                            $$t$$   $$i$$

  --------------------------------------------------------------- -------
eqnBlockInlineMath: true
```
(the extra newline in the table is important!)

You need `eqnBlockInlineMath: true` here so that pandoc doesn't force center alignment on math inside the table (as it unconditionally does for display math; the rendering shouldn't be otherwise affected, as Word treats any math that's alone in a paragraph as display math).

If you don't mind tinkering a bit, I believe the option of using tab stops to align equations should work the best in general, e.g.

```yaml
tableEqns: true
eqnBlockTemplate: |
   `<w:pPr><w:tabs><w:tab w:val="center" w:pos="4680" /><w:tab w:val="right" w:pos="9360" /></w:tabs></w:pPr><w:r><w:tab /></w:r>`{=openxml} $$t$$ `<w:r><w:tab /></w:r>`{=openxml} $$i$$
eqnBlockInlineMath: true
```

You'd have to manually specify tab stop positions, though (the values here, `4680` and `9360`, are appropriate for A4 with 1-inch margins)
