### ISSUE TITLE
Template in yaml does not work, but does when in markdown

### ISSUE THREAD

**Issue by svenboulanger** [lierdakil/pandoc-crossref#361]
I was experimenting with the template feature, notably `tableTemplate`.

This markdown file works:

```markdown
---
tableTemplate: $$tableTitle$$ $$i$$$$titleDelim$$ $$t$$ This is a test
---

Table: Name {#tbl:table_1}

| A | B |
|---|---|
| 1 | 2 |
```
`pandoc test.md -s --filter pandoc-crossref.exe -o test.docx`

But if I try the same thing providing metadata through the yaml file, it doesn't work:

```markdown
Table: Name {#tbl:table_1}

| A | B |
|---|---|
| 1 | 2 |
```

```yaml
standalone: true
metadata:
  tableTemplate: $$tableTitle$$ $$i$$$$titleDelim$$ $$t$$ This is a test
filters:
  - pandoc-crossref.exe
```

Instead of `Table 1: Name This is a test`, the result changes to `$$tableTitle$$ $$i$$$$titleDelim$$ $$t$$ This is a test`.

Note that if I use other variables in the template, like `tableTitle`, it does work even from the yaml file.
