### ISSUE TITLE
Cannot format figure/table caption prefix

### ISSUE THREAD

**Issue by et2010** [lierdakil/pandoc-crossref#71]
#### Description
Cannot format caption prefix.

#### Reproduction guide
- Make a `pandoc-crossref.yaml` file containing following lines:
```yaml
figureTitle: "图"
titleDelim: ".&nbsp;&nbsp;"
figureTemplate: **$$figureTitle$$$$i$$$$titleDelim$$**$$t$$
```
- Run pandoc to covert markdown to docx:
```sh
pandoc -f markdown -t docx -o main.docx --parse-raw --standalone --filter=pandoc-crossref -F pandoc-citeproc --reference-docx=reference.docx main.md
```

*Observed behaviour:*
The output docx file is not formatted based on the yaml file. Instead, default value of these variables is used. For example, figure caption is like:

Figure 1: Some Figure

Note that if I comment out the third line of the yaml file, or remove the double `*`s, it will be formatted correctly.

*Expected behaviour:*
Figure caption should be like this: 

**图1.**  Some Figure

#### System Info
- OS: Archlinux
- pandoc: 1.17.0.3-15
- pandoc-crossref: 0.2.1.3-2
- pandoc-citeproc: 0.9.1.1-23

#### Related issues
#8
